---
- name: Converge
  hosts: all
  roles:
    - role: ansible-loki
      vars:
        loki_version: 2.1.0
        promtail_use_docker: true
        promtail_config_server_listen: "{{ promtail_config_server_listen }}"
        promtail_config_server_port: 9080
