---
- name: Ensure .kube directory exists
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'

- name: Copy kubeconfig file
  copy:
    src: kubeconfig
    dest: /home/{{ ansible_user }}/.kube/config
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
